__name__ = 'wrapplotlib'
__description__ = 'A pythonic wrapper for matplotlib.'
__url__ = 'https://github.com/EmilianoJordan/WrapPlotLib'
__version__ = '0.0.1'
__author__ = 'Emiliano Jordan'
__author_email__ = 'emiliano.jordan+wpl@protonmail.com'
__licence__ = 'Apache-2.0'
